---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-example-app
  name: prometheus-example-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: web
  selector:
    app: prometheus-example-app
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
 labels:
   app: coo-demo
 name: coo-demo
spec:
 ports:
   - name: http
     port: 8080
   - name: metrics
     port: 9000
 selector:
     app: coo-demo